apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-openapi-samples
 
  annotations:
    github.com/project-slug: numaan/api-openapi-samples
spec:
  type: other
   owner: guest
  lifecycle: unknown
