# Combined catalog-info.yaml file for your root directory
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-openapi-samples
  description: Collection of OpenAPI sample definitions
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: numaan/api-openapi-samples
spec:
  type: service
  owner: team-apis
  lifecycle: production
  providesApis:
    - petstore-api
    - ecommerce-api
    # Add other APIs here as you create their definitions
---
# Petstore API Definition
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: Petstore API sample using OpenAPI v3
  tags:
    - rest
    - openapi
    - sample
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    github.com/project-slug: numaan/api-openapi-samples
spec:
  type: openapi
  lifecycle: production
  owner: team-apis
  definition:
    $text: ./openapi-v3/api-example.yaml
---
# E-commerce API Definition
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ecommerce-api
  description: E-commerce API sample using OpenAPI v3
  tags:
    - rest
    - openapi
    - ecommerce
  annotations:
    backstage.io/techdocs-ref: dir:./docs
    github.com/project-slug: numaan/api-openapi-samples
spec:
  type: openapi
  lifecycle: production
  owner: team-product
  definition:
    $text: ./openapi-v3/marketplace-catalog.yml
