# This is the main catalog-info.yaml file for your root directory
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-openapi-samples
  description: Collection of OpenAPI sample definitions
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: numaan/api-openapi-samples
spec:
  type: service
  owner: team-apis
  lifecycle: production
  providesApis:
    - petstore-api
    - ecommerce-api
    # Add other APIs here as you create their definitions
